export const PASSPORT_GAMIFICATION_TEXTS: Record<number, string> = {
  0: "Você acabou de atravessar o portal inicial do Passaporte das 9 Camadas. Reconhecer que existe um caminho a ser percorrido é o primeiro ato de coragem da consciência. Nesta aula de apresentação, você vislumbrou o mapa da sua mente e como cada camada foi desenhada para desconstruir ilusões e reconstruir sua verdade. O benefício de começar agora é a clareza; você não está mais andando às cegas. Sua jornada de despertar começou, e a Camada 1 está logo ali, esperando para revelar o que realmente acontece nos bastidores dos seus pensamentos.",
  1: "Parabéns, você atravessou a Camada 1 — O Despertar. Começar a perceber o que acontece dentro da sua mente é o ponto de virada de toda transformação. A grande descoberta aqui é que você não é seus pensamentos; você é o observador deles. Ao aplicar essa distância saudável na vida cotidiana, você pode começar a notar como o estresse e a ansiedade tendem a diminuir, pois você não mais se identifica com cada impulso mental. Esse novo nível de consciência favorece uma paz interior que antes parecia inalcançável. Mas este é apenas o começo. O que acontece quando você olha para o reflexo das suas reações? A Camada 2 — O Espelho está pronta para te mostrar como você responde ao mundo.",
  2: "Você concluiu a Camada 2 — O Espelho. Aprender a observar suas reações sem julgamento é uma arte refinada. Você descobriu que o mundo exterior é, muitas vezes, um reflexo do seu estado interno. Ao praticar a autoconsciência reflexiva, você pode começar a perceber que os conflitos externos perdem força à medida que você resolve o tumulto interno. Isso tende a ampliar sua capacidade de empatia e autoliderança. Agora que você entende como responde, é hora de questionar as lentes pelas quais você enxerga. A Camada 3 — O Filtro irá revelar os condicionamentos que distorcem sua percepção.",
  3: "A Camada 3 — O Filtro foi atravessada. Você agora compreende que a realidade que percebe é filtrada por crenças e experiências passadas. A nova perspectiva é que as 'lentes' podem ser trocadas. Limpar esses filtros pode ajudar a reduzir preconceitos e visões limitantes sobre si mesmo e sobre os outros. Você pode começar a perceber oportunidades onde antes via apenas obstáculos. Com os filtros mais limpos, a pergunta fundamental ressoa: Quem realmente sou eu sem essas distorções? Avance para a Camada 4 — A Identidade para descobrir sua essência.",
  4: "Você alcançou o coração da jornada na Camada 4 — A Identidade. A descoberta de que sua essência é maior do que sua história ou suas posses é libertadora. Você aprendeu a distinguir o 'Eu' autêntico das construções sociais. Aplicar esse conhecimento na vida cotidiana pode favorecer uma autoconfiança inabalável, fundamentada no ser e não no ter. Você tende a se sentir mais íntegro e menos dependente da aprovação externa. Mas por que, mesmo conhecendo sua essência, você ainda repete velhos hábitos? A Camada 5 — O Padrão irá expor os ciclos repetitivos que ainda tentam te dominar.",
  5: "A Camada 5 — O Padrão foi concluída. Identificar os ciclos de repetição comportamental é o primeiro passo para quebrá-los. Você descobriu que muitos desses padrões são automáticos e inconscientes. Ao trazer luz para esses comportamentos, você pode começar a perceber o momento exato em que o padrão tenta se manifestar, ganhando tempo para agir de forma diferente. Isso pode ajudar significativamente na superação de vícios emocionais e hábitos destrutivos. A liberdade está próxima. Na Camada 6 — A Escolha, você aprenderá a usar o espaço entre o estímulo e a resposta.",
  6: "Você agora domina a Camada 6 — A Escolha. O entendimento de que você possui o poder de escolher sua resposta é a definição de liberdade humana. Esta nova perspectiva transforma você de vítima em protagonista da própria vida. No dia a dia, isso pode favorecer decisões mais alinhadas com seus valores, reduzindo arrependimentos e aumentando sua eficácia pessoal. Você pode começar a perceber que as circunstâncias não têm mais poder absoluto sobre seu bem-estar. Como consolidar essas novas escolhas permanentemente? A Camada 7 — A Reprogramação mostrará o caminho da neuroplasticidade.",
  7: "A Camada 7 — A Reprogramação foi atravessada com sucesso. Você compreendeu as bases da neuroplasticidade e como construir novos caminhos neurais. A transformação não é mais apenas um desejo, mas um processo biológico e consciente. Ao implementar novos protocolos de pensamento e ação, você tende a solidificar mudanças que antes pareciam temporárias. Isso pode ajudar a criar uma nova realidade de forma sustentável e profunda. Agora, é hora de unir todas as partes. A Camada 8 — A Integração ensinará como viver essa nova consciência em harmonia total.",
  8: "Você concluiu a Camada 8 — A Integração. A união entre mente, emoção e comportamento é o que chamamos de integridade. Você descobriu como alinhar o que pensa, o que sente e o que faz. Na prática, isso tende a reduzir o conflito interno e a fadiga mental, gerando uma fluidez natural na vida. Você pode começar a perceber que a vida se torna menos uma luta e mais uma expressão da sua consciência integrada. O horizonte está aberto. Quem você pode se tornar a partir desta nova base? A Camada 9 — O Novo Olhar é a expansão final da sua jornada.",
  9: "Parabéns! Você atravessou a Camada 9 — O Novo Olhar e completou a Jornada das 9 Camadas. Você não apenas terminou um curso; você expandiu seu horizonte de possibilidades. A grande descoberta final é que a jornada da consciência nunca termina, mas agora você possui os olhos para ver a beleza e o potencial em cada momento. Aplicar este novo olhar pode ajudar a transformar desafios em aprendizado constante e sucessos em gratidão profunda. Você se tornou alguém capaz de enxergar além da superfície da vida. Você está pronto para o seu novo começo."
};

export const PASSPORT_MISSIONS: Record<number, { mission: string; protocol: string; checkList: string[] }> = {
  1: {
    mission: "Observe um pensamento repetitivo por 15 minutos.",
    protocol: "Sente-se em silêncio e apenas observe o fluxo da mente sem tentar mudar nada. Anote as palavras ou imagens que mais se repetem.",
    checkList: ["Encontrar um lugar silencioso", "Colocar um timer", "Apenas observar sem julgar", "Registrar a experiência"]
  },
  2: {
    mission: "Identifique um 'gatilho' emocional durante o dia.",
    protocol: "Sempre que sentir uma mudança brusca de humor, pare e pergunte: 'O que aconteceu agora que refletiu algo dentro de mim?'.",
    checkList: ["Estar presente", "Perceber a emoção", "Identificar a situação externa", "Anotar o reflexo interno"]
  },
  // ... rest of the missions will be added dynamically or stored here
};
