export type PowerQuestion = { id: string; level: number; text: string; options: [string, string, string] };

// 70 perguntas — 10 por nível — cada uma com 3 alternativas próprias (score 1, 2 e 3).
const raw: Record<number, [string, string, string, string][]> = {
  1: [
    ["Que tipo de conteúdo alimenta sua atenção logo ao acordar?", "Redes sociais e notícias aleatórias", "Depende do dia, às vezes algo útil", "Conteúdo escolhido de forma intencional"],
    ["Com que frequência você lê livros ou estuda algo que amplia sua capacidade?", "Quase nunca", "De vez em quando, sem rotina", "De forma constante toda semana"],
    ["Quanto do que você consome é escolhido por você e não pelo algoritmo?", "Quase nada, sigo o que aparece", "Uma parte, ainda me distraio bastante", "A maior parte é escolha consciente"],
    ["Como você lida com pensamentos repetitivos que tiram sua clareza?", "Fico preso neles sem perceber", "Percebo, mas demoro a sair", "Reconheço e redireciono rapidamente"],
    ["Seu ambiente favorece concentração?", "Vivo em dispersão constante", "Consigo focar em alguns momentos", "Organizo meu ambiente para focar"],
    ["Quando aprende uma ideia nova, o que costuma acontecer?", "Só consumo e esqueço", "Aplico raramente", "Transformo em prática rapidamente"],
    ["Como protege seu foco de conversas e conteúdos que não agregam?", "Não tenho filtro nenhum", "Evito às vezes", "Tenho limites claros e cumpro"],
    ["Você reserva momentos de silêncio ou organização mental?", "Nunca paro", "Raramente acontece", "Sim, faz parte da minha rotina"],
    ["Ao decidir algo importante, no que você se baseia?", "No impulso do momento", "Em opiniões de terceiros", "Em informação, reflexão e critério próprio"],
    ["O que aprendeu recentemente mudou algum comportamento seu?", "Não mudou nada", "Mudou um pouco", "Sim, mudei atitudes concretas"],
  ],
  2: [
    ["Suas decisões diárias estão alinhadas aos seus valores?", "Raramente percebo essa ligação", "Às vezes sim, às vezes não", "Na maior parte do tempo sim"],
    ["Você consegue identificar o que dá sentido à sua fase atual?", "Estou perdido nisso", "Tenho pistas, mas sem clareza", "Sei exatamente o que me move"],
    ["Onde encontra força quando enfrenta dificuldades?", "Não sei onde buscar", "Depende muito do momento", "Tenho uma base interior que me sustenta"],
    ["Como pratica gratidão sem ignorar os problemas reais?", "Não pratico", "Lembro apenas quando algo bom acontece", "Pratico com regularidade e realismo"],
    ["Como lida com crenças diferentes das suas?", "Costumo julgar", "Tolero, mas com desconforto", "Respeito e aprendo com a diferença"],
    ["Você tem espaço regular de reflexão, oração ou meditação?", "Nenhum", "Muito esporádico", "Sim, com constância"],
    ["Existem valores que você não negocia mesmo sob pressão?", "Ainda não defini", "Alguns, mas cedo com frequência", "Sim, e sustento minhas escolhas"],
    ["Como transforma valores em atitudes concretas?", "Fico só na intenção", "Faço quando é fácil", "Traduzo em atitudes práticas"],
    ["Sua rotina tem uma direção maior do que cumprir tarefas?", "Sinto que só cumpro obrigações", "Às vezes percebo sentido", "Sim, minha rotina serve a um propósito"],
    ["Que contribuição você quer deixar nas pessoas?", "Nunca pensei nisso", "Tenho uma vaga ideia", "Tenho clareza e ajo por isso"],
  ],
  3: [
    ["Como tem sido a qualidade da sua alimentação?", "Desorganizada e no automático", "Oscila bastante", "Cuidada e consciente na maior parte"],
    ["Quanto movimento físico faz parte da sua semana?", "Praticamente nenhum", "Um pouco, sem regularidade", "Atividade constante e planejada"],
    ["Como está sua regularidade de sono e descanso?", "Durmo mal com frequência", "Varia muito", "Tenho rotina de descanso estável"],
    ["Você percebe quando o corpo pede pausa?", "Só quando adoeço", "Percebo, mas ignoro", "Percebo e ajusto a rotina"],
    ["Quais hábitos mais afetam sua disposição hoje?", "Hábitos que me esgotam dominam", "Misturo bons e maus hábitos", "Meus hábitos sustentam minha energia"],
    ["Onde o autocuidado entra na sua rotina?", "Sempre fica por último", "Entra quando sobra tempo", "Está agendado como prioridade"],
    ["Você tem alguma atividade corporal que mantém com prazer?", "Nenhuma", "Comecei algumas e parei", "Sim, mantenho com constância"],
    ["Seu ambiente facilita escolhas físicas saudáveis?", "Atrapalha bastante", "Neutro", "Está organizado para me ajudar"],
    ["Quando a rotina aperta, o que acontece com o corpo?", "Abandono todos os cuidados", "Mantenho um ou outro", "Preservo o essencial sempre"],
    ["Qual mudança física seria realista começar esta semana?", "Não consigo imaginar nenhuma", "Tenho ideias, mas sem plano", "Já sei exatamente qual e quando"],
  ],
  4: [
    ["Você consegue nomear o que sente antes de reagir?", "Reajo sem perceber", "Às vezes percebo depois", "Reconheço a emoção antes de agir"],
    ["Quanto tempo leva para recuperar seu equilíbrio após um imprevisto?", "Dias inteiros", "Algumas horas", "Recupero rapidamente"],
    ["Você cria espaço entre a emoção e a decisão?", "Ajo no impulso", "Depende da situação", "Sim, faço uma pausa consciente"],
    ["Como comunica um incômodo?", "Exploto ou me calo", "Falo, mas com carga emocional", "Falo com clareza e respeito"],
    ["Que situações mais tiram você do centro?", "Quase tudo me desestabiliza", "Algumas específicas", "Poucas, e já sei lidar"],
    ["Quando sente medo ou insegurança, como responde?", "Paraliso ou fujo", "Hesito bastante", "Reconheço e sigo agindo"],
    ["Consegue ver sua responsabilidade sem se culpar por tudo?", "Ou culpo os outros ou me destruo", "Oscilo entre os dois", "Tenho equilíbrio nessa leitura"],
    ["Como lida com a frustração de algo que não funcionou?", "Desisto rápido", "Fico abalado, mas retomo", "Ajusto o método e continuo"],
    ["Tem alguma prática que organiza suas emoções?", "Nenhuma", "Uso raramente", "Sim, uso com frequência"],
    ["Qual resposta emocional você gostaria de substituir?", "Não tenho clareza", "Sei mais ou menos", "Sei exatamente qual e por qual trocar"],
  ],
  5: [
    ["Quanto tempo de presença real você oferece a quem ama?", "Quase nenhum", "Presença dividida com o celular", "Tempo dedicado e sem distração"],
    ["Consegue conversar sobre assuntos difíceis?", "Evito o assunto", "Converso, mas viro conflito", "Converso com maturidade"],
    ["Como demonstra respeito ao discordar de alguém da família?", "Elevo o tom", "Me fecho", "Escuto e exponho com respeito"],
    ["Percebe quando alguém próximo precisa de atenção?", "Raramente percebo", "Percebo quando é evidente", "Percebo e ajo antes de pedirem"],
    ["Como estão seus limites nas relações?", "Não sei dizer não", "Coloco limites de forma instável", "Tenho limites claros e saudáveis"],
    ["Como lida com conflitos não resolvidos?", "Deixo acumular", "Tento resolver e desisto", "Busco resolução de forma ativa"],
    ["Você consegue pedir desculpas quando erra?", "Muito difícil para mim", "Depende de quem seja", "Sim, reconheço e reparo"],
    ["Com que frequência cria momentos intencionais de convivência?", "Praticamente nunca", "Só em datas especiais", "Crio momentos regularmente"],
    ["Você escuta para compreender ou para responder?", "Já preparo minha resposta", "Depende do meu humor", "Escuto de verdade antes de falar"],
    ["Qual vínculo merece uma atitude concreta sua agora?", "Não tinha pensado nisso", "Tenho uma ideia vaga", "Sei exatamente qual e o que farei"],
  ],
  6: [
    ["Você sabe para onde seu dinheiro está indo?", "Não faço ideia", "Tenho uma noção aproximada", "Acompanho com clareza"],
    ["Como decide se uma compra cabe no seu planejamento?", "Compro por impulso", "Penso um pouco antes", "Comparo com meu planejamento"],
    ["Você organiza despesas antes de assumir compromissos novos?", "Nunca", "Às vezes", "Sempre organizo antes"],
    ["Existe reserva ou proteção compatível com sua realidade?", "Nenhuma", "Comecei, mas é instável", "Sim, mantenho de forma consistente"],
    ["Como separa desejo de prioridade financeira?", "Não consigo separar", "Consigo em parte", "Tenho critérios claros"],
    ["Você revisa suas metas financeiras periodicamente?", "Nunca revisei", "Raramente", "Reviso com frequência definida"],
    ["Quando surge uma despesa inesperada, o que acontece?", "Desestrutura tudo", "Aperta, mas dou um jeito", "Absorvo sem comprometer o plano"],
    ["Você consegue falar de dinheiro sem ansiedade dominar?", "A ansiedade domina", "Fico desconfortável", "Falo com tranquilidade e objetividade"],
    ["Que hábito financeiro simples poderia melhorar em 30 dias?", "Não sei por onde começar", "Tenho ideias soltas", "Já sei qual e como acompanhar"],
    ["Qual decisão financeira precisa de atenção primeiro?", "Está tudo confuso", "Tenho uma suspeita", "Sei exatamente qual é"],
  ],
  7: [
    ["Seu trabalho atual se aproxima da direção que você deseja?", "Está muito distante", "Em parte", "Está bem alinhado"],
    ["Quais competências precisa desenvolver para avançar?", "Não sei quais são", "Tenho uma ideia geral", "Sei exatamente quais são"],
    ["Você sabe que resultados quer alcançar na próxima fase?", "Nenhuma clareza", "Alguma clareza", "Objetivos definidos e mensuráveis"],
    ["Como mede seu desenvolvimento além das tarefas?", "Não meço", "Meço informalmente", "Uso indicadores concretos"],
    ["Que contribuição deseja fazer através do trabalho?", "Nunca refleti", "Penso às vezes", "Tenho clareza e busco isso"],
    ["Reserva tempo para aprender algo que aumenta seu valor?", "Nenhum tempo", "Quando sobra", "Tempo protegido na agenda"],
    ["Está deixando oportunidades passarem por falta de ação?", "Muitas", "Algumas", "Poucas, costumo agir"],
    ["Como decide entre caminhos profissionais diferentes?", "Fico paralisado", "Decido por pressão externa", "Uso critérios próprios e decido"],
    ["Que projeto faria você sentir que avançou de verdade?", "Não consigo nomear", "Tenho uma ideia inicial", "Sei exatamente qual é"],
    ["Qual primeiro movimento profissional pode fazer em 7 dias?", "Nenhum definido", "Ainda estou pensando", "Já sei o que farei e quando"],
  ],
};

export const powerQuestions: PowerQuestion[] = Object.entries(raw).flatMap(([lvl, items]) =>
  items.map((q, i) => ({
    id: `${lvl}-${i + 1}`,
    level: Number(lvl),
    text: q[0],
    options: [q[1], q[2], q[3]] as [string, string, string],
  })),
);
