import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { ArrowLeft, ArrowRight, Award, BarChart3, Brain, Check, ChevronDown, CircleHelp, Clock3, Flame, Gem, Goal, Heart, Lock, MessageCircle, Play, RotateCcw, Save, Sparkles, Target, Trophy, Volume2, VolumeX, Wallet, Users, Briefcase, BookOpen, Dumbbell, ShieldCheck, Zap } from "lucide-react";

export const Route = createFileRoute("/_authenticated/desbloqueie-poder")({
  head: () => ({ meta: [{ title: "Desbloqueie o Poder — Instituto Neuroconsciência" }, { name: "description", content: "Os 7 níveis da vida — diagnóstico, missão, ação e evolução." }] }),
  component: DesbloqueiePoder,
});

type Level = { id:number; name:string; title:string; question:string; icon:any; accent:string; areas:string[] };
type Answer = { text:string; score:number };
type Question = { id:string; level:number; text:string; answers:Answer[] };
type SavedState = { answers:Record<string,number>; completed:number[]; missions:Record<number,boolean>; plans:Record<number,Plan>; metas:Meta[]; protocols:string[]; points:number; sound:boolean; startedAt:string; lastAt:string };
type Plan = { change:string; action:string; when:string; first:string; track:string };
type Meta = { id:string; horizon:string; goal:string; result:string; steps:string[]; priorities:string[]; actions:string[]; obstacles:string[]; strategy:string; first:string; indicator:string; done:boolean };

const levels:Level[] = [
 {id:1,name:"MENTAL",title:"Alimente a mente que conduz sua vida",question:"O que você está colocando dentro da sua mente que está construindo a pessoa que você está se tornando?",icon:Brain,accent:"from-cyan-500/30 to-blue-600/10",areas:["informações","livros","músicas","vídeos","conversas","aprendizado","pensamentos","ambiente mental"]},
 {id:2,name:"ESPIRITUAL",title:"Encontre aquilo que dá sentido à sua caminhada",question:"O que existe dentro de você que continua de pé quando as circunstâncias tentam derrubar você?",icon:Sparkles,accent:"from-violet-500/30 to-fuchsia-600/10",areas:["significado","valores","propósito","fé","conexão","gratidão","esperança","serviço"]},
 {id:3,name:"MATERIAL / FÍSICO",title:"Cuide do corpo que sustenta sua jornada",question:"Se seu corpo é o veículo da sua jornada, como você tem tratado esse veículo?",icon:Dumbbell,accent:"from-emerald-500/30 to-teal-600/10",areas:["alimentação","movimento","descanso","autocuidado","hábitos físicos","disposição"]},
 {id:4,name:"EMOCIONAL",title:"Aprenda a viver suas emoções sem ser governado por elas",question:"Você está vivendo suas emoções ou permitindo que suas emoções decidam sua vida?",icon:Heart,accent:"from-rose-500/30 to-orange-600/10",areas:["consciência emocional","impulsividade","autorregulação","equilíbrio","comunicação","respostas diante das dificuldades"]},
 {id:5,name:"FAMILIAR",title:"Fortaleça os vínculos que fazem parte da sua história",question:"As pessoas que você ama estão recebendo apenas sua presença física ou também sua presença emocional?",icon:Users,accent:"from-amber-500/30 to-yellow-600/10",areas:["presença","diálogo","respeito","cuidado","limites","conflitos","qualidade dos relacionamentos"]},
 {id:6,name:"FINANCEIRO",title:"Transforme dinheiro em ferramenta, não em fonte de desordem",question:"Você está conduzindo seu dinheiro ou suas decisões financeiras estão conduzindo você?",icon:Wallet,accent:"from-lime-500/30 to-emerald-600/10",areas:["organização","gastos","planejamento","poupança","investimento","responsabilidade financeira"]},
 {id:7,name:"PROFISSIONAL",title:"Construa uma vida profissional que tenha significado",question:"O trabalho que você realiza hoje está construindo a vida profissional que deseja viver amanhã?",icon:Briefcase,accent:"from-blue-500/30 to-indigo-600/10",areas:["satisfação","competência","desenvolvimento","propósito","contribuição","planejamento","direção profissional"]},
];

const stems:string[][] = [
 ["Quando você começa o dia, que tipo de conteúdo costuma alimentar primeiro sua atenção?","Com que frequência você escolhe conscientemente livros, aulas ou conteúdos que ampliam sua capacidade?","Quanto do conteúdo que você consome é escolhido por intenção e não apenas pelo algoritmo?","Como você percebe pensamentos repetitivos que diminuem sua clareza?","Seu ambiente costuma favorecer concentração ou dispersão?","Quando encontra uma ideia nova, você costuma aplicá-la ou apenas consumi-la?","Como você protege seu foco de conversas e conteúdos que não agregam?","Você reserva algum momento para silêncio, reflexão ou organização mental?","Quando precisa tomar uma decisão importante, quais informações você usa para decidir?","O que você tem aprendido recentemente que realmente mudou algum comportamento?"],
 ["O quanto suas decisões diárias estão alinhadas aos valores que considera importantes?","Você consegue identificar o que dá significado à fase de vida em que está?","Quando enfrenta uma dificuldade, onde encontra força para continuar?","Como você pratica gratidão sem ignorar os problemas reais?","Você respeita crenças diferentes das suas ao conversar sobre espiritualidade?","Você tem algum espaço regular para reflexão, oração, meditação ou silêncio, conforme suas crenças?","Quais valores você não quer negociar mesmo sob pressão?","De que maneira você transforma seus valores em atitudes concretas?","Você sente que sua rotina tem uma direção maior do que simplesmente cumprir tarefas?","Que contribuição você gostaria que sua passagem pela vida deixasse nas pessoas?"],
 ["Como você tem cuidado da qualidade da sua alimentação no cotidiano?","Quanto movimento físico faz parte da sua semana de forma consistente?","Como tem sido sua regularidade de descanso e recuperação?","Você percebe com facilidade quando seu corpo está pedindo pausa ou cuidado?","Quais hábitos físicos aumentam ou reduzem sua disposição?","Como você organiza sua rotina para não deixar o autocuidado sempre por último?","Você tem alguma atividade corporal que consegue manter com prazer?","O quanto seu ambiente facilita escolhas físicas mais saudáveis para você?","Quando sua rotina aperta, quais cuidados com o corpo você preserva?","Qual pequena mudança física seria mais realista começar nesta semana?"],
 ["Você consegue nomear o que sente antes de reagir a uma situação difícil?","Quando algo sai diferente do esperado, quanto tempo leva para recuperar seu equilíbrio?","Você costuma agir no impulso ou cria espaço entre emoção e decisão?","Como você comunica incômodo sem transformar a conversa em ataque?","Que situações mais facilmente tiram você do seu centro?","Quando sente medo ou insegurança, como costuma responder?","Você consegue reconhecer sua parcela de responsabilidade sem se culpar por tudo?","Como você lida com frustração quando uma tentativa não funciona?","Você tem alguma prática que ajuda a organizar suas emoções antes de agir?","Qual resposta emocional você gostaria de substituir por uma resposta mais consciente?"],
 ["Quanto tempo de presença verdadeira você oferece às pessoas importantes para você?","Você consegue conversar sobre assuntos difíceis sem fugir ou atacar?","Como demonstra respeito quando discorda de alguém da família?","Você percebe quando alguém próximo precisa de atenção, mesmo sem pedir?","Quais limites são necessários para preservar relações saudáveis?","Como costuma lidar com conflitos que permanecem sem resolução?","Você consegue pedir desculpas quando percebe que errou?","Com que frequência cria momentos intencionais de convivência?","Você escuta para compreender ou já prepara sua resposta enquanto a outra pessoa fala?","Qual vínculo familiar merece uma atitude concreta sua agora?"],
 ["Você sabe com clareza para onde seu dinheiro está indo neste momento?","Como decide se uma compra cabe ou não no seu planejamento?","Você costuma organizar despesas antes de assumir novos compromissos?","Existe uma reserva ou estratégia de proteção compatível com sua realidade atual?","Como você separa desejo de prioridade financeira?","Você revisa periodicamente suas metas e compromissos financeiros?","Quando surge uma despesa inesperada, como sua rotina reage?","Você consegue falar sobre dinheiro sem deixar que ansiedade conduza suas decisões?","Quais hábitos financeiros pequenos poderiam melhorar sua organização nos próximos 30 dias?","Qual decisão financeira concreta precisa de atenção primeiro?"],
 ["O quanto seu trabalho atual se aproxima da direção profissional que deseja?","Quais competências você precisa desenvolver para avançar?","Você sabe quais resultados concretos espera alcançar na próxima fase profissional?","Como mede seu próprio desenvolvimento além de tarefas concluídas?","Que tipo de contribuição você deseja fazer por meio do seu trabalho?","Você reserva tempo para aprender algo que aumenta seu valor profissional?","Quais oportunidades você está deixando passar por falta de direção ou ação?","Como decide entre caminhos profissionais quando existem várias opções?","Que projeto ou resultado faria você sentir que avançou de verdade?","Qual primeiro movimento profissional você pode executar nos próximos sete dias?"],
];

function buildQuestions():Question[]{
 return stems.flatMap((arr,li)=>arr.map((text,i)=>({id:`${li+1}-${i+1}`,level:li+1,text,answers:[
  {text:["Raramente ou ainda não tenho clareza","Ainda acontece de forma irregular","É uma prática consciente e consistente"][Math.min(2,Math.floor((i+li)%3))],score:1},
  {text:["Às vezes, quando consigo","Tenho melhorado, mas oscilo","Faço isso na maioria das vezes"][Math.min(2,Math.floor((i+1)%3))],score:2},
  {text:["Quero começar a mudar isso agora","Já tenho consciência e quero aprofundar","Faz parte das minhas escolhas e ações"][Math.min(2,Math.floor((i+2)%3))],score:3},
 ]}))));
}
const questions=buildQuestions();

function blankState():SavedState{return{answers:{},completed:[],missions:{},plans:{},metas:[],protocols:[],points:0,sound:true,startedAt:new Date().toISOString(),lastAt:new Date().toISOString()};}
function makeDiagnostic(name:string,level:Level,vals:number[],mission:string){
 const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0; const score=Math.round(vals.reduce((a,b)=>a+b,0));
 const reading=avg>=2.45?"um momento de maior consciência e consistência":avg>=1.75?"um momento intermediário, no qual já existem recursos, mas eles ainda precisam de direção e repetição":"um momento que pede atenção intencional e pequenas ações estruturadas";
 const strengths=avg>=2.45?`Você já demonstra recursos importantes em ${level.areas.slice(0,4).join(", ")}.`:avg>=1.75?`Há sinais positivos em ${level.areas.slice(0,2).join(" e ")}, que podem servir como ponto de apoio.`:`Seu principal recurso agora é a consciência de que esta área merece espaço e ação deliberada.`;
 const attention=avg>=2.45?`O ponto de atenção é transformar consistência em profundidade, evitando acomodação.`:avg>=1.75?`O ponto de atenção é reduzir a oscilação: escolher poucas práticas e repeti-las até que façam parte da rotina.`:`O ponto de atenção é sair da intenção abstrata e criar uma primeira ação pequena, observável e com prazo.`;
 return `DIAGNÓSTICO DE AUTOPERCEPÇÃO E DESENVOLVIMENTO\n\n${name}, seu resultado no Nível ${level.id} — ${level.name} — indica ${reading}. Sua pontuação foi ${score}/30. Este resultado não é diagnóstico médico, psiquiátrico ou psicológico; ele é um retrato educativo das respostas que você escolheu neste momento.\n\nO tema central deste nível é: ${level.title}. A pergunta que orienta sua jornada é: “${level.question}” Ao olhar para suas respostas, o mais importante não é buscar uma nota perfeita. É perceber quais comportamentos já existem, quais dependem de intenção e quais precisam ser transformados em prática.\n\nPONTOS FORTES\n${strengths} Esses recursos são importantes porque uma mudança sustentável não começa do zero: ela aproveita o que já funciona e amplia sua capacidade de escolha.\n\nPONTOS DE ATENÇÃO\n${attention} Observe especialmente ${level.areas.slice(0,3).join(", ")}. Não tente corrigir tudo ao mesmo tempo. Escolha o ponto que tem maior efeito sobre sua próxima decisão e trabalhe nele primeiro.\n\nCOMO INTERPRETAR ESTE MOMENTO\nO resultado sugere que sua evolução pode acontecer pela sequência consciência → escolha → ação → repetição. Em vez de esperar uma mudança de identidade antes de agir, use uma ação concreta para construir evidência de que você consegue conduzir esse comportamento. Se surgir resistência, trate-a como informação para ajustar o método, não como prova de incapacidade.\n\nPOSSIBILIDADE DE EVOLUÇÃO\nNos próximos dias, transforme esta leitura em um experimento. Defina quando a ação acontecerá, qual será o primeiro passo e qual sinal mostrará que você avançou. Registre o que aconteceu e ajuste o que for necessário. A meta não é perfeição; é aumentar a qualidade das decisões que você repete.\n\nSUA MISSÃO\n${mission}\n\n${name}, agora você tem um ponto de partida mais claro. O próximo avanço não depende de pensar mais sobre a mudança, mas de executar a próxima ação definida e voltar para registrar o que aconteceu. Este módulo é uma ferramenta de autopercepção e desenvolvimento pessoal e não substitui acompanhamento profissional.`;
}

function missionFor(level:Level,avg:number){
 const action=level.id===1?"Escolha 20 minutos por dia durante 3 dias para consumir apenas um conteúdo intencional que amplie uma habilidade importante e registre uma aplicação prática.":level.id===2?"Reserve 10 minutos em 3 dias desta semana para refletir sobre um valor essencial e escreva uma atitude concreta que o represente no mesmo dia.":level.id===3?"Escolha uma mudança física simples e sustentável, defina três dias e registre o que fez e como percebeu sua disposição, sem buscar diagnóstico clínico.":level.id===4?"Em uma situação emocionalmente difícil nesta semana, faça uma pausa consciente antes de responder, nomeie o que sente e escolha uma resposta deliberada.":level.id===5?"Escolha uma pessoa importante, marque um momento de 20 minutos sem distrações e faça uma conversa em que você escute antes de tentar resolver.":level.id===6?"Durante os próximos 3 dias, registre suas principais despesas e, ao final, escolha uma única prioridade de organização compatível com sua realidade.":"Reserve 30 minutos para definir uma competência profissional prioritária, o resultado que deseja melhorar e a primeira ação de desenvolvimento que executará em 7 dias.";
 return avg>=2.45?`${action} Depois, registre o que pode ser aprofundado.`:action;
}

function playTone(enabled:boolean,kind="click"){if(!enabled)return; try{const C=window.AudioContext||((window as any).webkitAudioContext);const c=new C();const o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);const f=kind==="win"?660:kind==="select"?440:300;o.frequency.value=f;o.type="sine";g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(kind==="win"?.07:.025,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.18);o.start();o.stop(c.currentTime+.2)}catch{}}

function DesbloqueiePoder(){
 const [name,setName]=useState("Jöweslëy"); const [uid,setUid]=useState(""); const [state,setState]=useState<SavedState>(blankState()); const [screen,setScreen]=useState<"home"|"quiz"|"result"|"mission"|"mentor"|"meta"|"evolution"|"premium">("home"); const [level,setLevel]=useState(1); const [qi,setQi]=useState(0); const [mentor,setMentor]=useState(""); const [mentorReply,setMentorReply]=useState(""); const [metaGoal,setMetaGoal]=useState(""); const [horizon,setHorizon]=useState("1 mês"); const [showReset,setShowReset]=useState(false); const [toast,setToast]=useState("");
 const qLevel=questions.filter(q=>q.level===level); const current=qLevel[qi]; const lvl=levels[level-1]; const completed=state.completed.length; const totalPoints=state.points; const pct=Math.round(completed/7*100);
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();const id=data.user?.id||"local";setUid(id);const {data:p}=await supabase.from("profiles").select("display_name").eq("id",id).maybeSingle();if(p?.display_name)setName(p.display_name);const raw=localStorage.getItem(`desbloqueie-poder:${id}`);if(raw)try{setState(JSON.parse(raw))}catch{}})()},[]);
 useEffect(()=>{if(uid){const next={...state,lastAt:new Date().toISOString()};localStorage.setItem(`desbloqueie-poder:${uid}`,JSON.stringify(next))}},[state,uid]);
 useEffect(()=>{const inactive=Date.now()-new Date(state.lastAt||Date.now()).getTime()>3*86400000;if(inactive&&state.completed.length)setToast(`Bem-vindo de volta, ${name}. Seu progresso foi preservado.`)},[]);
 const scores=useMemo(()=>qLevel.map(q=>state.answers[q.id]||0),[qLevel,state.answers]);
 const choose=(score:number)=>{if(!current)return;playTone(state.sound,"select");setState(s=>({...s,answers:{...s.answers,[current.id]:score},points:s.points+1}));if(qi<9)setQi(qi+1);else{const vals=qLevel.map(q=>state.answers[q.id]|| (q.id===current.id?score:0));const unique=vals.filter(Boolean);const avg=unique.reduce((a,b)=>a+b,0)/10;const mission=missionFor(lvl,avg);setState(s=>({...s,completed:Array.from(new Set([...s.completed,level])),missions:{...s.missions,[level]:false},points:s.points+10}));setScreen("result");playTone(state.sound,"win")}};
 const diagnostic=makeDiagnostic(name,lvl,scores.map((v,i)=>v||0),missionFor(lvl,(scores.filter(Boolean).reduce((a,b)=>a+b,0)/(scores.filter(Boolean).length||1))));
 const begin=(n:number)=>{setLevel(n);setQi(0);setScreen("quiz");playTone(state.sound)};
 const savePlan=(plan:Plan)=>{setState(s=>({...s,plans:{...s.plans,[level]:plan},missions:{...s.missions,[level]:true},points:s.points+20}));setScreen("home");setToast("Missão registrada no seu histórico.");playTone(state.sound,"win")};
 const buildMeta=()=>{if(!metaGoal.trim())return;const meta:Meta={id:crypto.randomUUID(),horizon,goal:metaGoal,result:`Chegar a um resultado observável para “${metaGoal}” dentro de ${horizon}.`,steps:["Definir o resultado observável","Escolher prioridades","Executar a primeira ação","Revisar e ajustar"],priorities:["Primeira ação","Consistência","Acompanhamento"],actions:[`Executar uma ação inicial relacionada a ${metaGoal}`],obstacles:["Falta de tempo","Distrações","Mudança de prioridade"],strategy:"Reduzir a meta a ações pequenas, agendadas e registradas; revisar o progresso no intervalo escolhido.",first:`Defina agora o primeiro passo de ${metaGoal} e marque quando será feito.`,indicator:"Uma evidência concreta registrada a cada ciclo.",done:false};setState(s=>({...s,metas:[...s.metas,meta],points:s.points+15}));setMetaGoal("");setScreen("home");setToast("Meta criada e salva.")};
 const askMentor=()=>{if(!mentor.trim())return;const currentMission=state.plans[level]?.action||missionFor(lvl,2);setMentorReply(`${name}, considerando o Nível ${level} — ${lvl.name} — e o que você relatou, não tente resolver a jornada inteira de uma vez. Seu contexto atual pede uma decisão simples: ${currentMission} Se isso estiver grande demais, reduza o primeiro passo para algo que caiba em 10 minutos e defina um horário. Depois registre o resultado. Se você estiver atrasado, não apague o que já fez: retome pela última ação incompleta. Se seu objetivo mudou, registre a mudança e ajuste a missão, preservando o histórico. A pergunta útil agora é: qual ação observável você consegue concluir hoje?\n\nSua próxima ação: escreva em uma frase o que fará, quando fará e qual evidência mostrará que terminou.`);setState(s=>({...s,protocols:[...s.protocols,`${new Date().toLocaleString()} — ${mentor}`],points:s.points+5}));playTone(state.sound,"select")};
 const reset=()=>{const fresh=blankState();setState(fresh);localStorage.removeItem(`desbloqueie-poder:${uid}`);setShowReset(false);setScreen("home");setToast("Jornada reiniciada.")};
 const nav=(s:any)=>{setScreen(s);playTone(state.sound)};
 return <div className="min-h-screen bg-background text-foreground">
  <div className="fixed inset-0 -z-10 bg-[radial-gradient(circle_at_15%_10%,hsl(var(--primary)/.14),transparent_32%),radial-gradient(circle_at_85%_30%,hsl(var(--gold)/.08),transparent_28%)]" />
  <header className="sticky top-0 z-40 border-b border-border/60 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-3"><button onClick={()=>nav("home")} className="flex items-center gap-2 text-sm font-medium"><ArrowLeft className="h-4 w-4"/><span className="hidden sm:inline">Área de membros</span></button><div className="hidden md:flex items-center gap-5 text-[10px] uppercase tracking-[.18em] text-muted-foreground"><button onClick={()=>nav("home")}>Início</button><button onClick={()=>nav("evolution")}>Minha evolução</button><button onClick={()=>nav("meta")}>Metas</button><button onClick={()=>nav("mentor")}>Anti-procrastinação</button><button onClick={()=>nav("premium")}>Premium</button></div><button onClick={()=>setState(s=>({...s,sound:!s.sound}))} className="glass rounded-full p-2" aria-label="Som on off">{state.sound?<Volume2 className="h-4 w-4 text-gold"/>:<VolumeX className="h-4 w-4"/>}</button></div></header>
  <main className="mx-auto max-w-7xl px-4 py-6 sm:py-10">
   {toast&&<div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full border border-primary/30 bg-surface px-5 py-3 text-sm shadow-elevated">{toast}<button onClick={()=>setToast("")} className="ml-3 text-muted-foreground">×</button></div>}
   {screen==="home"&&<>
    <section className="relative overflow-hidden rounded-[2rem] border border-primary/20 bg-gradient-to-br from-slate-950 via-blue-950/70 to-background shadow-elevated">
      <div className="grid items-stretch lg:grid-cols-[1.05fr_.95fr]">
       <div className="relative z-10 p-7 sm:p-10 lg:p-12"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.2em] text-primary"><Sparkles className="h-3.5 w-3.5"/> Protocolo premium</div><h1 className="max-w-2xl font-display text-4xl leading-[.98] sm:text-6xl">DESBLOQUEIE O PODER <span className="text-primary">DA SUA MENTE</span></h1><p className="mt-4 max-w-xl text-lg text-white/75">Os 7 níveis da vida. <span className="text-white">Uma única vida para cuidar.</span></p><p className="mt-3 max-w-xl text-sm leading-6 text-white/55">Do diagnóstico à sua missão diária. Uma jornada de autopercepção para compreender, escolher, agir, registrar e evoluir.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>begin(Math.min(7,completed+1))} className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-slate-950 shadow-glow">{completed?"Continuar jornada":"Começar diagnóstico"}<ArrowRight className="h-4 w-4"/></button><button onClick={()=>nav("evolution")} className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-5 py-3 text-sm text-white/80">Ver meu progresso</button></div></div>
       <div className="relative min-h-[360px] overflow-hidden"><img src="/desbloqueie-poder-banner.svg" alt="Área de membros premium — Desbloqueie o Poder da Sua Mente" className="absolute inset-0 h-full w-full object-cover object-top"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-transparent to-transparent lg:bg-gradient-to-l lg:from-transparent lg:via-transparent lg:to-slate-950/60"/></div>
      </div>
    </section>
    <section className="mt-5 grid gap-3 sm:grid-cols-4"><Stat icon={<Trophy/>} label="Progresso geral" value={`${pct}%`}/><Stat icon={<Award/>} label="Níveis concluídos" value={`${completed}/7`}/><Stat icon={<Zap/>} label="Pontuação" value={String(totalPoints)}/><Stat icon={<Flame/>} label="Sequência" value={state.completed.length?`${Math.min(state.completed.length,7)} nível${state.completed.length>1?"s":""}`:"Comece hoje"}/></section>
    <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-primary">Meu progresso</p><h2 className="mt-1 font-display text-3xl">7 níveis. 7 áreas. Uma jornada.</h2></div><span className="text-sm text-muted-foreground">{completed}/7 níveis concluídos</span></div><div className="mt-5 grid gap-3 md:grid-cols-7">{levels.map((l,i)=>{const done=state.completed.includes(l.id),locked=i>0&&!state.completed.includes(i);const Icon=l.icon;return <button key={l.id} disabled={locked} onClick={()=>begin(l.id)} className={`group relative overflow-hidden rounded-2xl border p-4 text-left transition ${done?"border-primary/50 bg-primary/10":"border-border bg-surface"} ${locked?"cursor-not-allowed opacity-55":"hover:-translate-y-1 hover:border-primary/40"}`}><div className={`absolute inset-0 bg-gradient-to-br ${l.accent} opacity-60`}/><div className="relative"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-widest text-muted-foreground">0{l.id}</span>{done?<Check className="h-4 w-4 text-primary"/>:<Icon className="h-4 w-4 text-muted-foreground"/>}</div><p className="mt-5 text-sm font-semibold">{l.name}</p><p className="mt-1 line-clamp-2 text-[11px] text-muted-foreground">{l.title}</p>{locked&&<Lock className="absolute right-0 bottom-0 h-3.5 w-3.5 text-muted-foreground"/>}</div></button>})}</div></section>
    <section className="mt-10 grid gap-4 lg:grid-cols-3"><ActionCard icon={<Target/>} title="Missão atual" text={state.plans[level]?.action||missionFor(lvl,2)} button="Ver missão" onClick={()=>nav("mission")}/><ActionCard icon={<Goal/>} title="Construtor de metas" text="Transforme meta em resultado, etapas, ações, prazos e acompanhamento." button="Criar meta" onClick={()=>nav("meta")}/><ActionCard icon={<Brain/>} title="Anti-procrastinação" text="Descreva o que está evitando e transforme o bloqueio em uma primeira ação." button="Abrir mentor" onClick={()=>nav("mentor")}/></section>
    <section className="mt-10 rounded-3xl border border-border bg-surface p-6 sm:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl bg-primary/10 p-3"><ShieldCheck className="h-6 w-6 text-primary"/></div><div><h3 className="font-display text-2xl">DIAGNOSTICAR → COMPREENDER → PERCEBER → ESCOLHER → AGIR → REGISTRAR → EVOLUIR</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Você não precisa transformar sua vida inteira hoje. Precisa descobrir qual nível merece sua atenção e dar o próximo passo. Os resultados são educativos e voltados à autopercepção e desenvolvimento pessoal.</p></div></div></section>
   </>}
   {screen==="quiz"&&<Quiz name={name} level={lvl} qi={qi} current={current} total={10} onBack={()=>nav("home")} onChoose={choose}/>} 
   {screen==="result"&&<Result name={name} level={lvl} diagnostic={diagnostic} score={scores.reduce((a,b)=>a+b,0)} onContinue={()=>setScreen("mission")} onHome={()=>nav("home")}/>} 
   {screen==="mission"&&<Mission name={name} level={lvl} plan={state.plans[level]} done={!!state.missions[level]} onSave={savePlan} onHome={()=>nav("home")}/>} 
   {screen==="mentor"&&<Mentor name={name} level={lvl} value={mentor} setValue={setMentor} reply={mentorReply} onAsk={askMentor} onHome={()=>nav("home")}/>} 
   {screen==="meta"&&<MetaBuilder goal={metaGoal} setGoal={setMetaGoal} horizon={horizon} setHorizon={setHorizon} metas={state.metas} onBuild={buildMeta} onToggle={(id)=>setState(s=>({...s,metas:s.metas.map(m=>m.id===id?{...m,done:!m.done}:m),points:s.points+10}))}/>} 
   {screen==="evolution"&&<Evolution name={name} state={state} onReset={()=>setShowReset(true)}/>} 
   {screen==="premium"&&<Premium/>}
  </main>
  {showReset&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-border bg-surface p-6 shadow-elevated"><h3 className="font-display text-2xl">Reiniciar jornada?</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Isso apagará seu progresso, respostas, missões, metas, pontuação e histórico. Deseja realmente começar novamente?</p><div className="mt-6 flex gap-3"><button onClick={()=>setShowReset(false)} className="flex-1 rounded-full border border-border px-4 py-3">Cancelar</button><button onClick={reset} className="flex-1 rounded-full bg-destructive px-4 py-3 text-white">Reiniciar</button></div></div></div>}
 </div>
}

function Stat({icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-2xl border border-border bg-surface p-4"><div className="flex items-center gap-2 text-primary">{icon}<span className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</span></div><p className="mt-2 font-display text-2xl">{value}</p></div>}
function ActionCard({icon,title,text,button,onClick}:{icon:any;title:string;text:string;button:string;onClick:()=>void}){return <div className="rounded-3xl border border-border bg-surface p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</div><h3 className="mt-4 font-display text-xl">{title}</h3><p className="mt-2 min-h-[52px] text-sm leading-6 text-muted-foreground">{text}</p><button onClick={onClick} className="mt-5 inline-flex items-center gap-2 rounded-full border border-border px-4 py-2 text-xs font-semibold hover:border-primary/50">{button}<ArrowRight className="h-3.5 w-3.5"/></button></div>}
function Quiz({name,level,qi,current,total,onBack,onChoose}:{name:string;level:Level;qi:number;current:Question;total:number;onBack:()=>void;onChoose:(s:number)=>void}){const Icon=level.icon;return <section className="mx-auto max-w-3xl"><button onClick={onBack} className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/> Voltar</button><div className={`overflow-hidden rounded-[2rem] border border-border bg-gradient-to-br ${level.accent} p-6 sm:p-10`}><div className="flex items-center justify-between"><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-primary"><Icon className="h-4 w-4"/> Nível {level.id} — {level.name}</span><span className="text-xs text-muted-foreground">Pergunta {qi+1}/{total}</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-primary transition-all duration-500" style={{width:`${(qi+1)/total*100}%`}}/></div><p className="mt-10 text-sm uppercase tracking-widest text-muted-foreground">Olá, {name}</p><h1 className="mt-2 font-display text-3xl leading-tight sm:text-4xl">{current.text}</h1><p className="mt-3 text-sm text-muted-foreground">Responda pela alternativa que mais se aproxima da sua realidade agora.</p><div className="mt-8 space-y-3">{current.answers.map((a,i)=><button key={i} onClick={()=>onChoose(a.score)} className="group flex w-full items-center gap-4 rounded-2xl border border-border bg-background/60 p-5 text-left transition hover:-translate-y-0.5 hover:border-primary/50 hover:bg-primary/5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-border text-sm font-semibold group-hover:border-primary group-hover:text-primary">{String.fromCharCode(65+i)}</span><span className="text-sm leading-6">{a.text}</span><ArrowRight className="ml-auto h-4 w-4 opacity-40 group-hover:opacity-100"/></button>)}</div></div><p className="mt-5 text-center text-[11px] text-muted-foreground">Diagnóstico de autopercepção e desenvolvimento — sem finalidade clínica.</p></section>}
function Result({name,level,diagnostic,score,onContinue,onHome}:{name:string;level:Level;diagnostic:string;score:number;onContinue:()=>void;onHome:()=>void}){return <section className="mx-auto max-w-4xl"><div className="relative overflow-hidden rounded-[2rem] border border-primary/30 bg-gradient-to-br from-slate-950 via-blue-950/60 to-background p-7 text-center sm:p-12"><div className="pointer-events-none absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_50%_0%,hsl(var(--primary)/.5),transparent_40%)]"/><div className="relative"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-primary/40 bg-primary/10 shadow-glow"><Trophy className="h-9 w-9 text-primary"/></div><p className="mt-5 text-[10px] uppercase tracking-[.25em] text-primary">Parabéns, {name}!</p><h1 className="mt-2 font-display text-4xl">Nível {level.id} concluído</h1><p className="mt-2 text-muted-foreground">{level.name} · {score}/30 pontos</p><div className="mx-auto mt-8 grid max-w-xl grid-cols-2 gap-3 sm:grid-cols-3"><Stat icon={<Award/>} label="Nível" value={`${level.id}/7`}/><Stat icon={<BarChart3/>} label="Pontuação" value={`${score}/30`}/><Stat icon={<Sparkles/>} label="Próximo" value={level.id<7?`Nível ${level.id+1}`:"Conclusão"}/></div></div></div><div className="mt-5 rounded-3xl border border-border bg-surface p-6"><h2 className="font-display text-2xl">Seu diagnóstico</h2><div className="mt-4 max-h-[520px] overflow-auto whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{diagnostic}</div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><button onClick={onContinue} className="flex-1 rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground">Ver minha missão</button><button onClick={onHome} className="rounded-full border border-border px-6 py-3">Voltar ao início</button></div></section>}
function Mission({name,level,plan,done,onSave,onHome}:{name:string;level:Level;plan?:Plan;done:boolean;onSave:(p:Plan)=>void;onHome:()=>void}){const [p,setP]=useState<Plan>(plan||{change:"",action:missionFor(level,2),when:"Hoje",first:"",track:""});return <section className="mx-auto max-w-3xl"><button onClick={onHome} className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/> Início</button><div className="rounded-[2rem] border border-primary/30 bg-surface p-6 sm:p-10"><div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-[10px] uppercase tracking-widest text-primary"><Target className="h-3.5 w-3.5"/> Minha missão</div><h1 className="mt-5 font-display text-4xl">{name}, transforme consciência em ação.</h1><p className="mt-3 text-muted-foreground">Nível {level.id} — {level.name}</p><div className="mt-8 rounded-2xl border border-primary/20 bg-primary/5 p-5"><p className="text-[10px] uppercase tracking-widest text-primary">Missão de implementação</p><p className="mt-3 text-lg leading-8">{p.action}</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2">{[["change","O que preciso mudar?"],["action","O que vou fazer?"],["when","Quando vou fazer?"],["first","Qual será meu primeiro passo?"],["track","Como vou acompanhar?"]].map(([k,l])=><label key={k} className="text-xs font-semibold text-muted-foreground">{l}<textarea value={(p as any)[k]} onChange={e=>setP({...p,[k]:e.target.value})} rows={k==="action"?3:2} className="mt-2 w-full resize-none rounded-2xl border border-border bg-background p-3 text-sm text-foreground outline-none focus:border-primary"/></label>)}</div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={()=>onSave(p)} className="flex-1 rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground">{done?"Atualizar missão":"Marcar missão como concluída"}</button><button onClick={onHome} className="rounded-full border border-border px-6 py-3">Depois</button></div></div></section>}
function Mentor({name,level,value,setValue,reply,onAsk,onHome}:{name:string;level:Level;value:string;setValue:(v:string)=>void;reply:string;onAsk:()=>void;onHome:()=>void}){return <section className="mx-auto max-w-3xl"><button onClick={onHome} className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/> Início</button><div className="rounded-[2rem] border border-border bg-surface p-6 sm:p-10"><div className="flex items-center gap-3"><div className="rounded-2xl bg-primary/10 p-3 text-primary"><MessageCircle/></div><div><p className="text-[10px] uppercase tracking-widest text-primary">Anti-procrastinação</p><h1 className="font-display text-3xl">Pare de adiar. Comece a agir.</h1></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{name}, descreva com o máximo de detalhes o que você está evitando, há quanto tempo, por que precisa fazer, o que sente quando pensa em começar e o que já tentou fazer.</p><textarea value={value} onChange={e=>setValue(e.target.value)} placeholder="O que você está procrastinando?" rows={7} className="mt-6 w-full rounded-2xl border border-border bg-background p-4 text-sm outline-none focus:border-primary"/><button onClick={onAsk} className="mt-4 w-full rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground">Gerar protocolo de execução</button>{reply&&<div className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-5"><p className="whitespace-pre-wrap text-sm leading-7">{reply}</p></div>}<p className="mt-5 text-center text-xs italic text-muted-foreground">Agora não pense em terminar tudo. Execute o primeiro passo.</p><p className="mt-5 text-[10px] text-muted-foreground">Conteúdo educativo de autopercepção e desenvolvimento pessoal; não substitui acompanhamento profissional.</p></div></section>}
function MetaBuilder({goal,setGoal,horizon,setHorizon,metas,onBuild,onToggle}:{goal:string;setGoal:(v:string)=>void;horizon:string;setHorizon:(v:string)=>void;metas:Meta[];onBuild:()=>void;onToggle:(id:string)=>void}){return <section className="mx-auto max-w-4xl"><div className="rounded-[2rem] border border-border bg-surface p-6 sm:p-10"><p className="text-[10px] uppercase tracking-widest text-primary">Construtor de metas</p><h1 className="mt-2 font-display text-4xl">Meta → Resultado → Etapas → Ações</h1><div className="mt-7 grid gap-4 sm:grid-cols-[1fr_180px]"><textarea value={goal} onChange={e=>setGoal(e.target.value)} rows={4} placeholder="Qual é a meta que você deseja alcançar?" className="rounded-2xl border border-border bg-background p-4 text-sm outline-none focus:border-primary"/><select value={horizon} onChange={e=>setHorizon(e.target.value)} className="h-fit rounded-2xl border border-border bg-background p-4 text-sm"><option>Hoje</option><option>1 semana</option><option>1 mês</option><option>3 meses</option><option>6 meses</option><option>1 ano</option></select></div><button onClick={onBuild} className="mt-4 rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground">Salvar e acompanhar meta</button></div><div className="mt-6 space-y-4">{metas.map(m=><article key={m.id} className="rounded-3xl border border-border bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-primary/10 px-3 py-1 text-[10px] uppercase tracking-widest text-primary">{m.horizon}</span><h2 className="mt-3 font-display text-2xl">{m.goal}</h2><p className="mt-2 text-sm text-muted-foreground">{m.result}</p></div><button onClick={()=>onToggle(m.id)} className={`rounded-full px-4 py-2 text-xs font-semibold ${m.done?"bg-primary text-primary-foreground":"border border-border"}`}>{m.done?"Concluída":"Marcar concluída"}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><InfoBox title="Etapas" items={m.steps}/><InfoBox title="Ações" items={m.actions}/><InfoBox title="Obstáculos" items={m.obstacles}/><InfoBox title="Estratégia" items={[m.strategy,m.indicator]}/></div></article>)}</div></section>}
function InfoBox({title,items}:{title:string;items:string[]}){return <div className="rounded-2xl border border-border/70 p-4"><p className="text-[10px] uppercase tracking-widest text-primary">{title}</p><ul className="mt-2 space-y-1 text-sm text-muted-foreground">{items.map((x,i)=><li key={i}>• {x}</li>)}</ul></div>}
function Evolution({name,state,onReset}:{name:string;state:SavedState;onReset:()=>void}){return <section className="mx-auto max-w-5xl"><div className="rounded-[2rem] border border-border bg-surface p-6 sm:p-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] uppercase tracking-widest text-primary">Minha evolução</p><h1 className="mt-2 font-display text-4xl">Sua jornada, {name}.</h1></div><button onClick={onReset} className="inline-flex items-center gap-2 rounded-full border border-destructive/30 px-4 py-2 text-xs text-destructive"><RotateCcw className="h-3.5 w-3.5"/> Reiniciar jornada</button></div><div className="mt-8 h-3 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-primary transition-all" style={{width:`${state.completed.length/7*100}%`}}/></div><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>{state.completed.length}/7 níveis concluídos</span><span>{state.points} pontos</span></div><div className="mt-8 grid gap-3 sm:grid-cols-4"><Stat icon={<Award/>} label="Níveis" value={`${state.completed.length}/7`}/><Stat icon={<Target/>} label="Missões" value={String(Object.values(state.missions).filter(Boolean).length)}/><Stat icon={<Goal/>} label="Metas" value={String(state.metas.length)}/><Stat icon={<BookOpen/>} label="Protocolos" value={String(state.protocols.length)}/></div><div className="mt-8 rounded-3xl border border-border p-5"><p className="text-[10px] uppercase tracking-widest text-primary">Linha do tempo</p><div className="mt-4 space-y-3">{levels.map(l=><div key={l.id} className="flex items-center gap-4"><div className={`flex h-9 w-9 items-center justify-center rounded-full ${state.completed.includes(l.id)?"bg-primary text-primary-foreground":"bg-white/5 text-muted-foreground"}`}>{state.completed.includes(l.id)?<Check className="h-4 w-4"/>:l.id}</div><div><p className="text-sm font-semibold">Nível {l.id} — {l.name}</p><p className="text-xs text-muted-foreground">{state.completed.includes(l.id)?"Concluído e registrado":"Aguardando sua jornada"}</p></div></div>)}</div></div></div></section>}
function Premium(){const items=["Aulas dos 7 Níveis da Vida","7 Aplicativos Interativos de Desenvolvimento Pessoal","Central de Comando","Robô Decodificador de Livros","Mapa da Vida","Formação Prática em PNL","Mais Esperto que o Diabo — Mentoria NeuroLeitura","Desbloqueie o Poder da Sua Mente — Mentoria baseada em princípios dos ensinamentos de Jesus"];return <section className="mx-auto max-w-4xl"><div className="rounded-[2rem] border border-primary/30 bg-gradient-to-br from-slate-950 via-blue-950/60 to-background p-7 sm:p-12"><div className="flex items-center gap-3"><Gem className="text-primary"/><span className="text-[10px] uppercase tracking-[.25em] text-primary">Área de membros premium 🔐</span></div><h1 className="mt-5 font-display text-4xl">Sua próxima etapa de desenvolvimento está aqui.</h1><p className="mt-4 text-muted-foreground">Para ativar sua área premium, entre em contato pelo WhatsApp e envie o e-mail utilizado na compra.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{items.map((x,i)=><div key={i} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm"><Check className="h-4 w-4 shrink-0 text-primary"/>{x}</div>)}</div><a href="https://wa.me/message/YNNTLWLFBDWOP1" target="_blank" rel="noopener noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 font-semibold text-primary-foreground"><MessageCircle className="h-4 w-4"/> Ativar área premium</a></div></section>}
