/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTreinamentoPremiumRouteImport } from './routes/_authenticated/treinamento-premium'
import { Route as AuthenticatedReprogramacaoMentalRouteImport } from './routes/_authenticated/reprogramacao-mental'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated/comunidade'
import { Route as AuthenticatedCentroOperacionalRouteImport } from './routes/_authenticated/centro-operacional'
import { Route as AuthenticatedCartaFuturoRouteImport } from './routes/_authenticated/carta-futuro'
import { Route as AuthenticatedBonusRouteImport } from './routes/_authenticated/bonus'
import { Route as AuthenticatedModuloSlugRouteImport } from './routes/_authenticated/modulo.$slug'
import { Route as AuthenticatedTreinamentoPremiumNivelSlugRouteImport } from './routes/_authenticated/treinamento-premium.nivel.$slug'
import { Route as AuthenticatedTreinamentoPremiumCamadaLayerNumberRouteImport } from './routes/_authenticated/treinamento-premium.camada.$layerNumber'
import { Route as AuthenticatedHeroJourneyArchetypeIdRouteImport } from './routes/_authenticated/hero-journey/archetype.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreinamentoPremiumRoute =
  AuthenticatedTreinamentoPremiumRouteImport.update({
    id: '/treinamento-premium',
    path: '/treinamento-premium',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReprogramacaoMentalRoute =
  AuthenticatedReprogramacaoMentalRouteImport.update({
    id: '/reprogramacao-mental',
    path: '/reprogramacao-mental',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentroOperacionalRoute =
  AuthenticatedCentroOperacionalRouteImport.update({
    id: '/centro-operacional',
    path: '/centro-operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartaFuturoRoute =
  AuthenticatedCartaFuturoRouteImport.update({
    id: '/carta-futuro',
    path: '/carta-futuro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBonusRoute = AuthenticatedBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModuloSlugRoute = AuthenticatedModuloSlugRouteImport.update({
  id: '/modulo/$slug',
  path: '/modulo/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinamentoPremiumNivelSlugRoute =
  AuthenticatedTreinamentoPremiumNivelSlugRouteImport.update({
    id: '/nivel/$slug',
    path: '/nivel/$slug',
    getParentRoute: () => AuthenticatedTreinamentoPremiumRoute,
  } as any)
const AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute =
  AuthenticatedTreinamentoPremiumCamadaLayerNumberRouteImport.update({
    id: '/camada/$layerNumber',
    path: '/camada/$layerNumber',
    getParentRoute: () => AuthenticatedTreinamentoPremiumRoute,
  } as any)
const AuthenticatedHeroJourneyArchetypeIdRoute =
  AuthenticatedHeroJourneyArchetypeIdRouteImport.update({
    id: '/hero-journey/archetype/$id',
    path: '/hero-journey/archetype/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/carta-futuro': typeof AuthenticatedCartaFuturoRoute
  '/centro-operacional': typeof AuthenticatedCentroOperacionalRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reprogramacao-mental': typeof AuthenticatedReprogramacaoMentalRoute
  '/treinamento-premium': typeof AuthenticatedTreinamentoPremiumRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/modulo/$slug': typeof AuthenticatedModuloSlugRoute
  '/hero-journey/archetype/$id': typeof AuthenticatedHeroJourneyArchetypeIdRoute
  '/treinamento-premium/camada/$layerNumber': typeof AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute
  '/treinamento-premium/nivel/$slug': typeof AuthenticatedTreinamentoPremiumNivelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/carta-futuro': typeof AuthenticatedCartaFuturoRoute
  '/centro-operacional': typeof AuthenticatedCentroOperacionalRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reprogramacao-mental': typeof AuthenticatedReprogramacaoMentalRoute
  '/treinamento-premium': typeof AuthenticatedTreinamentoPremiumRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/modulo/$slug': typeof AuthenticatedModuloSlugRoute
  '/hero-journey/archetype/$id': typeof AuthenticatedHeroJourneyArchetypeIdRoute
  '/treinamento-premium/camada/$layerNumber': typeof AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute
  '/treinamento-premium/nivel/$slug': typeof AuthenticatedTreinamentoPremiumNivelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/bonus': typeof AuthenticatedBonusRoute
  '/_authenticated/carta-futuro': typeof AuthenticatedCartaFuturoRoute
  '/_authenticated/centro-operacional': typeof AuthenticatedCentroOperacionalRoute
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/reprogramacao-mental': typeof AuthenticatedReprogramacaoMentalRoute
  '/_authenticated/treinamento-premium': typeof AuthenticatedTreinamentoPremiumRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/modulo/$slug': typeof AuthenticatedModuloSlugRoute
  '/_authenticated/hero-journey/archetype/$id': typeof AuthenticatedHeroJourneyArchetypeIdRoute
  '/_authenticated/treinamento-premium/camada/$layerNumber': typeof AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute
  '/_authenticated/treinamento-premium/nivel/$slug': typeof AuthenticatedTreinamentoPremiumNivelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/bonus'
    | '/carta-futuro'
    | '/centro-operacional'
    | '/comunidade'
    | '/ferramentas'
    | '/home'
    | '/jornada'
    | '/perfil'
    | '/reprogramacao-mental'
    | '/treinamento-premium'
    | '/api/chat'
    | '/modulo/$slug'
    | '/hero-journey/archetype/$id'
    | '/treinamento-premium/camada/$layerNumber'
    | '/treinamento-premium/nivel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/bonus'
    | '/carta-futuro'
    | '/centro-operacional'
    | '/comunidade'
    | '/ferramentas'
    | '/home'
    | '/jornada'
    | '/perfil'
    | '/reprogramacao-mental'
    | '/treinamento-premium'
    | '/api/chat'
    | '/modulo/$slug'
    | '/hero-journey/archetype/$id'
    | '/treinamento-premium/camada/$layerNumber'
    | '/treinamento-premium/nivel/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/bonus'
    | '/_authenticated/carta-futuro'
    | '/_authenticated/centro-operacional'
    | '/_authenticated/comunidade'
    | '/_authenticated/ferramentas'
    | '/_authenticated/home'
    | '/_authenticated/jornada'
    | '/_authenticated/perfil'
    | '/_authenticated/reprogramacao-mental'
    | '/_authenticated/treinamento-premium'
    | '/api/chat'
    | '/_authenticated/modulo/$slug'
    | '/_authenticated/hero-journey/archetype/$id'
    | '/_authenticated/treinamento-premium/camada/$layerNumber'
    | '/_authenticated/treinamento-premium/nivel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treinamento-premium': {
      id: '/_authenticated/treinamento-premium'
      path: '/treinamento-premium'
      fullPath: '/treinamento-premium'
      preLoaderRoute: typeof AuthenticatedTreinamentoPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reprogramacao-mental': {
      id: '/_authenticated/reprogramacao-mental'
      path: '/reprogramacao-mental'
      fullPath: '/reprogramacao-mental'
      preLoaderRoute: typeof AuthenticatedReprogramacaoMentalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centro-operacional': {
      id: '/_authenticated/centro-operacional'
      path: '/centro-operacional'
      fullPath: '/centro-operacional'
      preLoaderRoute: typeof AuthenticatedCentroOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carta-futuro': {
      id: '/_authenticated/carta-futuro'
      path: '/carta-futuro'
      fullPath: '/carta-futuro'
      preLoaderRoute: typeof AuthenticatedCartaFuturoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bonus': {
      id: '/_authenticated/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof AuthenticatedBonusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulo/$slug': {
      id: '/_authenticated/modulo/$slug'
      path: '/modulo/$slug'
      fullPath: '/modulo/$slug'
      preLoaderRoute: typeof AuthenticatedModuloSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinamento-premium/nivel/$slug': {
      id: '/_authenticated/treinamento-premium/nivel/$slug'
      path: '/nivel/$slug'
      fullPath: '/treinamento-premium/nivel/$slug'
      preLoaderRoute: typeof AuthenticatedTreinamentoPremiumNivelSlugRouteImport
      parentRoute: typeof AuthenticatedTreinamentoPremiumRoute
    }
    '/_authenticated/treinamento-premium/camada/$layerNumber': {
      id: '/_authenticated/treinamento-premium/camada/$layerNumber'
      path: '/camada/$layerNumber'
      fullPath: '/treinamento-premium/camada/$layerNumber'
      preLoaderRoute: typeof AuthenticatedTreinamentoPremiumCamadaLayerNumberRouteImport
      parentRoute: typeof AuthenticatedTreinamentoPremiumRoute
    }
    '/_authenticated/hero-journey/archetype/$id': {
      id: '/_authenticated/hero-journey/archetype/$id'
      path: '/hero-journey/archetype/$id'
      fullPath: '/hero-journey/archetype/$id'
      preLoaderRoute: typeof AuthenticatedHeroJourneyArchetypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTreinamentoPremiumRouteChildren {
  AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute: typeof AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute
  AuthenticatedTreinamentoPremiumNivelSlugRoute: typeof AuthenticatedTreinamentoPremiumNivelSlugRoute
}

const AuthenticatedTreinamentoPremiumRouteChildren: AuthenticatedTreinamentoPremiumRouteChildren =
  {
    AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute:
      AuthenticatedTreinamentoPremiumCamadaLayerNumberRoute,
    AuthenticatedTreinamentoPremiumNivelSlugRoute:
      AuthenticatedTreinamentoPremiumNivelSlugRoute,
  }

const AuthenticatedTreinamentoPremiumRouteWithChildren =
  AuthenticatedTreinamentoPremiumRoute._addFileChildren(
    AuthenticatedTreinamentoPremiumRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBonusRoute: typeof AuthenticatedBonusRoute
  AuthenticatedCartaFuturoRoute: typeof AuthenticatedCartaFuturoRoute
  AuthenticatedCentroOperacionalRoute: typeof AuthenticatedCentroOperacionalRoute
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedReprogramacaoMentalRoute: typeof AuthenticatedReprogramacaoMentalRoute
  AuthenticatedTreinamentoPremiumRoute: typeof AuthenticatedTreinamentoPremiumRouteWithChildren
  AuthenticatedModuloSlugRoute: typeof AuthenticatedModuloSlugRoute
  AuthenticatedHeroJourneyArchetypeIdRoute: typeof AuthenticatedHeroJourneyArchetypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBonusRoute: AuthenticatedBonusRoute,
  AuthenticatedCartaFuturoRoute: AuthenticatedCartaFuturoRoute,
  AuthenticatedCentroOperacionalRoute: AuthenticatedCentroOperacionalRoute,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedReprogramacaoMentalRoute: AuthenticatedReprogramacaoMentalRoute,
  AuthenticatedTreinamentoPremiumRoute:
    AuthenticatedTreinamentoPremiumRouteWithChildren,
  AuthenticatedModuloSlugRoute: AuthenticatedModuloSlugRoute,
  AuthenticatedHeroJourneyArchetypeIdRoute:
    AuthenticatedHeroJourneyArchetypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
